version: "3"
services:
  prometheus:
    image: "wubloader_prometheus:latest"
    command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    - "--storage.tsdb.path=/prometheus"
    - "--storage.tsdb.retention=30d"
    - "--web.console.libraries=/usr/share/prometheus/console_libraries"
    - "--web.console.templates=/usr/share/prometheus/consoles"
    restart: "on-failure"
    volumes:
    - "/storage/wubloader-metrics/prometheus:/prometheus"
    ports:
    - "9090:9090"
  grafana:
    image: "grafana/grafana"
    restart: "on-failure"
    volumes:
    - "/storage/wubloader-metrics/grafana:/var/lib/grafana"
    ports:
    - "1338:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_NAME: "Main Org."
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
